server:
  port: 8040
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.30.8.74:8848
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他的微服务
          enabled: true
      routes:
        - id: between_route
          uri: lb://user-center
          predicates:
            - TimeBetween=上午9:00,下午11:00
          filters:
            - AddRequestHeader=X-Request-Foo, Bar
            - PreLog=a,b
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always